name: quran_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.7.2
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.3
  skeletonizer: ^1.4.3
  loading_animation_widget: ^1.3.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.8.0
  marquee: ^2.3.0
  sqflite: ^2.4.2
  path: ^1.9.1
  visibility_detector: ^0.4.0+2
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  image_path_android: "assets/images/ic_launcher.png"
  image_path_ios: "assets/images/ic_launcher.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#186351"
  adaptive_icon_background: "#186351"
  adaptive_icon_foreground: "assets/images/ic_launcher.png"

flutter:
  assets: 
    - assets/models/
    - assets/images/
  uses-material-design: true
